services:
  trino-coordinator:
    image: trinodb/trino:472
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./trino-config/coordinator/config.properties:/etc/trino/config.properties
      - ./trino-config/catalog/:/etc/trino/catalog/
    networks:
      - lakehouse

  trino-worker-1:
    image: trinodb/trino:472
    container_name: trino-worker-1
    volumes:
      - ./trino-config/worker/config.properties:/etc/trino/config.properties
      - ./trino-config/catalog/:/etc/trino/catalog/
    networks:
      - lakehouse

  trino-worker-2:
    image: trinodb/trino:472
    container_name: trino-worker-2
    volumes:
      - ./trino-config/worker/config.properties:/etc/trino/config.properties
      - ./trino-config/catalog/:/etc/trino/catalog/
    networks:
      - lakehouse

networks:
  lakehouse:
    name: lakehouse
    driver: bridge
